name: Running Backend Tests With Coverage

on: 
  push:
    branches:
      - group31-fall24
      - master
      - group5-fall24
  pull_request:
    branches:
      - group31-fall24
      - master
      - group5-fall24


jobs:
  run_backend_tests_Coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
          cd Code/backend
          touch .env
          echo RECIPES_DB_URI=${{ secrets.TESTING_DB_URI }} >> .env
          echo RECIPES_NS=${{ secrets.DB_NAME }} >> .env
          echo PORT=${{ secrets.API_PORT }} >> .env
          echo GMAIL=${{ secrets.GMAIL }} >> .env
          npm install
      continue-on-error: true  

    - name: Run backend tests with coverage
      run: |
          cd Code/backend
          npm test -- --coverage
      continue-on-error: true  

    - name: Verify coverage report
      run: ls -la Code/backend/coverage
      continue-on-error: true  

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN1 }}
        files: Code/backend/coverage/lcov.info
      continue-on-error: true 
