name: Check the source code
on:
  pull_request:
    branches:
      - master
      - group31-fall24
      - group5-fall24
  push:
    branches:
      - master
      - group31-fall24
      - group5-fall24

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
            cd Code/backend
            npm install
        continue-on-error: true 
      - name: Code Formatter
        run: |
            cd Code/backend
            npm run format
        continue-on-error: true 
